### ISSUE TITLE
Infer MyST notebook files by looking for ```{code-cell} blocks

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/MyST-NB#120]
I'm writing up the documentation on MyST notebooks in the CLI, and I found that it is a bit cumbersome to ask users to explicitly create Jupytext headers for their MyST notebooks. It's easy if you're using Jupytext, but if somebody wanted to create a MyST notebook from scratch, they won't be able to remember:

```yaml
jupytext:
  formats: md:myst
  text_representation:
    extension: .md
    format_name: myst
    format_version: '0.8'
    jupytext_version: 1.4.1+dev
kernelspec:
  display_name: Python 3
  language: python
  name: python3
```

Could we add an extra check here: https://github.com/ExecutableBookProject/MyST-NB/blob/0919b71ab5efc33823007bc2d92d64a8c7d217da/myst_nb/converter.py#L46

such that if no `jupytext:` block was found in the metadata, it scanned the lines for one that began with ` ```{code-cell} ` and, if so, assumes that this is a myst-nb file? We could even raise a warning in this case saying "I'm inferring that this is a myst notebook, you should explicitly make it so by adding this YAML metadata"

**Comment by chrisjsewell** [comment]
You don't need all of that though, just:

```yaml
jupytext:
  text_representation:
    format_name: myst
kernelspec:
  display_name: Python 3
  name: python3
```

Is that really that cumbersome? If not it could be way more time-consuming, because you then have to read through the entirety of every markdown file to check for `{code-cell}`, rather than now it only needs to read the first few lines
