### ISSUE TITLE
SVG outputs are rendered as strings in LaTeX

### ISSUE THREAD

**Issue by JensHeinrich** [executablebooks/MyST-NB#370]
### Describe the problem

If the output of an command is of type `image/svg+xml` it is included as string output in LaTeX file

### Steps to reproduce

1. Create notebook with code cell like this
```python
import chess
import chess.svg

board = chess.Board()
board.push(chess.Move.from_uci("d2d4"))
chess.svg.board(board, size=350)
```
2. Generate Output
3. Try to create pdf 

### Additional context

This will probably be fixed by fixing #178

**Comment by JensHeinrich** [comment]
Thank you very much
This works nicely

**Comment by chrisjsewell** [comment]
Since #380, this is easy to configure for with https://www.sphinx-doc.org/en/master/usage/extensions/imgconverter.html:

```python
extensions =  ["sphinx.ext.imgconverter"]
nb_mime_priority_overrides = [
     # builder name, mime type, priority
	("latex", "image/svg+xml", 15)
]
```

`sphinx.ext.imgconverter` is not enabled by default though, so latex should also not be.
Also, as noted in the link, there are alternative options for SVG -> latex conversion, like https://github.com/missinglinkelectronics/sphinxcontrib-svg2pdfconverter

this could/should be added to the documentation

**Comment by martinlarsalbert** [comment]
For the ```_config.yml``` (jupyter-book) this would be:

```
sphinx:
  config:
    nb_mime_priority_overrides:
        - - latex
          - "image/svg+xml"
          - 15
```

And it seems that the higher the number (15) the higher the priority will be.

**Comment by chrisjsewell** [comment]
Indeed, it is detailed here: https://myst-nb.readthedocs.io/en/latest/render/format_code_cells.html#outputs-mime-priority

**Comment by joelostblom** [comment]
I'm trying to render SVGs in pdflatex output from jupyter book and after spending many hours on it I still can't seem to find a solution. I tried putting the following inside `_config.yml` but it does not seem to have an effect:

```
sphinx:
  config:
    nb_render_priority:
      latex:
        - "application/pdf"
        - "image/svg+xml"
        - "image/png"
        - "image/jpeg"
        - "text/latex"
        - "text/markdown"
        - "text/plain"
```

Next I tried adding the following 

```
sphinx:
  config:
    nb_mime_priority_overrides:
        - - latex
          - "image/svg+xml"
          - 15
```

which does insert svg as rasters, but the resolution is so low that it is unusable. Is there any way to pass a dpi argument to the imagemagick converter in the yaml config file?

I also tried using https://github.com/missinglinkelectronics/sphinxcontrib-svg2pdfconverter but I don't understand how to write my config file for jupyter book to enable this extension, any tips would be helpful (I tried adding the cairo convert under "extra extensions", but my svgs still odn't show up. (I can't use inkscape or resvg)).

I attach the notebook file I have been trying to render
[svg-test.ipynb.txt](https://github.com/executablebooks/MyST-NB/files/12052375/svg-test.ipynb.txt)
