### ISSUE TITLE
Scroll output horizontally with large Pandas dataframes

### ISSUE THREAD

**Issue by dprada** [executablebooks/MyST-NB#453]
### Describe the bug

When a pandas dataframe is wider than the output cell, the result is a dataframe printed out beyond the limits of the web when compiled with sphinx. This happens even with the cell tag "output_scroll":

![image](https://user-images.githubusercontent.com/531231/193632478-9a298239-fc73-4a0d-9974-e975b2131f97.png)

I would have expected a horizontal scroll bar as we can see in the notebook opened with jupyter lab:

![image](https://user-images.githubusercontent.com/531231/193632987-d33f1473-2a4a-46f8-98f2-e29d961bc0da.png)

Is the tag "output_scroll" working only vertically?

Thanks in advance for your help with this issue.

### Reproduce the bug

Code to reproduce the behavior:

```python
import pandas as pd
test_dict = {jj*20:[ii] for ii,jj in enumerate('abcdefghijklm')}
pd.DataFrame(test_dict)
```

The sphinx extensions used are:
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.intersphinx',
    'sphinx.ext.mathjax',
    'sphinx.ext.todo',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.githubpages',
    'sphinxcontrib.bibtex',
    'sphinx.ext.extlinks',
    'sphinx_remove_toctrees',
    'sphinx_copybutton',
    'myst_nb'
]

### List your environment

Versions used:
```
python: 3.9
sphinx: 5.1.1
myst-nb: 0.16.0
myst-parser: 0.18.0
```

Theme:
html_theme = 'sphinx_rtd_theme'

**Comment by chrisjsewell** [comment]
Heya what theme are you using

**Comment by dprada** [comment]
html_theme = 'sphinx_rtd_theme'

Is this affecting the default behavior?

**Comment by chrisjsewell** [comment]
In sphinx-book-theme I know there is this added CSS: https://github.com/executablebooks/sphinx-book-theme/blob/eb1b6baf098b27605e8f2b7b2979b17ebf1b9540/src/sphinx_book_theme/assets/styles/extensions/_myst-nb.scss#L21
I think that is what you are after

it may be that we want to move this into myst-nb

**Comment by dprada** [comment]
I added those lines to my _static/custom.css file, but it doesn't solve the problem.
I also tried adding some lines to define the same for y and x (height and width) -not sure if this makes sense-:
```
  @mixin cell-scroll {
    @include scrollbar-style();
    max-height: 24em;
    overflow-y: auto;
    max-width: 24em;
    overflow-x: auto;
    @media print {
      max-height: unset;
      overflow-y: visible;
      max-width: unset;
      overflow-x: visible;
    }
```

@chrisjsewell: Thanks for your support, although I couldn't fix it yet. I just wonder... you can scroll horizontally through a wide dataframe, right? In that case, this is not a bug and I have to play a bit to see if I can get the default behavior with the tag `output_scroll` or `scroll-output`.

**Comment by chrisjsewell** [comment]
@dprada thats SASS not CSS 😉 it needs to be "converted"

**Comment by dprada** [comment]
I am not a CSS/HTML developer but I'll work on it. I should learn a bit 😉.

Please, let's keep this issue open until I check that those lines in the custom.css file show the horizontal scrollbar.

**Comment by dprada** [comment]
The following lines in the _static/custom.css file do the job (with the tag 'scroll-output'):

```css
div.cell.tag_scroll-output div.cell_output {
         max-height: 24em;
         overflow-y: auto;
         max-width: 100%;
         overflow-x: auto;
}

div.cell.tag_scroll-output div.cell_output::-webkit-scrollbar {
         width: 0.3rem;
         height: 0.3rem;
}

div.cell.tag_scroll-output div.cell_output::-webkit-scrollbar-thumb {
         background: #c1c1c1;
         border-radius: 0.25rem;
}

div.cell.tag_scroll-output div.cell_output::-webkit-scrollbar-thumb:hover {
         background: #a0a0a0;
}

@media print {
         div.cell.tag_scroll-output div.cell_output {
                 max-height: unset;
                 overflow-y: visible;
                 max-width: unset;
                 overflow-x: visible;
        }
}
```
🎉 It works perfectly as I expected! 🎉 

Thanks a lot, @chrisjsewell.

Finally, would you support adding these lines (and the same for tags 'output_scroll' and 'scroll-input') to myst-nb? I can make a PR...
